name: Apply (reusable)

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      dir:
        required: true
        type: string

    secrets:
      role_arn:
        required: true
      health_check_url:
        required: false

jobs:
  apply:
    name: Apply / ${{ inputs.env }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    defaults:
      run:
        working-directory: ${{ inputs.dir }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.role_arn }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - run: terraform init

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ inputs.env }}
          path: ${{ inputs.dir }}

      - run: terraform apply -auto-approve tfplan

      - name: Post-apply health check
        if: ${{ secrets.health_check_url != ""}}
        run: |
          sleep 30
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${{ secrets.health_check_url }}")
          [ "$STATUS" = "200" ] || { echo "Health check failed — HTTP $STATUS"; exit 1; }