name: Terraform Pipeline

on:
  pull_request:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:

  changes:
    name: Detect changed paths
    runs-on: ubuntu-latest
    outputs:
      qa:      ${{ steps.filter.outputs.qa }}
      staging: ${{ steps.filter.outputs.staging }}
      prod:    ${{ steps.filter.outputs.prod }}
      modules: ${{ steps.filter.outputs.modules }}

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            qa:
              - 'environments/qa/**'
            staging:
              - 'environments/staging/**'
            prod:
              - 'environments/prod/**'
            modules:
              - 'modules/**'

  #! PLAN
  plan-qa:
    needs: changes
    if: needs.changes.outputs.qa == 'true' || needs.changes.outputs.modules == 'true'
    uses: ./.github/workflows/_plan.yaml
    secrets:
      role_arn: ${{ vars.AWS_ROLE_ARN_QA }}
    with:
      env: qa
      dir: environments/qa
      aws_region: ${{ vars.AWS_REGION }}
      tf_version: ${{ vars.TF_VERSION }}

  plan-staging:
    needs: changes
    if: needs.changes.outputs.staging == 'true' || needs.changes.outputs.modules == 'true'
    uses: ./.github/workflows/_plan.yaml
    secrets:
      role_arn: ${{ vars.AWS_ROLE_ARN_STAGING }}
    with:
      env: staging
      dir: environments/staging
      aws_region: ${{ vars.AWS_REGION }}
      tf_version: ${{ vars.TF_VERSION }}

  plan-prod:
    needs: changes
    if: needs.changes.outputs.prod == 'true' || needs.changes.outputs.modules == 'true'
    uses: ./.github/workflows/_plan.yaml
    secrets:
      role_arn: ${{ vars.AWS_ROLE_ARN_PROD }}
    with:
      env: prod
      dir: environments/prod
      aws_region: ${{ vars.AWS_REGION }}
      tf_version: ${{ vars.TF_VERSION }}

  
  #! APPLY
  apply-qa:
    needs: [changes, plan-qa]
    if: github.event_name == 'push' &&
        (needs.changes.outputs.qa == 'true' || needs.changes.outputs.modules == 'true')
    uses: ./.github/workflows/_apply.yaml
    secrets:
      role_arn: ${{ vars.AWS_ROLE_ARN_QA }}
    with:
      env: qa
      dir: environments/qa
      health_check_url: ${{ vars.HEALTH_CHECK_URL_QA }}

  apply-staging:
    needs: [changes, plan-staging, apply-qa]
    if: github.event_name == 'push' &&
        (needs.changes.outputs.staging == 'true' || needs.changes.outputs.modules == 'true')
    uses: ./.github/workflows/_apply.yaml
    secrets:
      role_arn: ${{ vars.AWS_ROLE_ARN_STAGING }}
    with:
      env: staging
      dir: environments/staging
      health_check_url: ${{ vars.HEALTH_CHECK_URL_STAGING }}

  apply-prod:
    needs: [changes, plan-prod, apply-staging]
    if: github.event_name == 'push' &&
        (needs.changes.outputs.prod == 'true' || needs.changes.outputs.modules == 'true')
    uses: ./.github/workflows/_apply.yaml
    secrets:
      role_arn: ${{ vars.AWS_ROLE_ARN_PROD }}
    with:
      env: prod
      dir: environments/prod
      health_check_url: ${{ vars.HEALTH_CHECK_URL_PROD }}